title: "My movie page"
name: "MMP"
description: "A development site"
domain: "localhost:4000"

url: "http://localhost:4000"
cdn: "http://localhost:4000/assets/"
img: "http://localhost:4000/assets/img/"
ico: "http://localhost:4000/assets/ico/"
css: "http://localhost:4000/assets/css/"

safe: false
future: false
show_drafts: true