title: "My movie page"
description: "A media diary, a small collage, a dumb blog"
domain: "www.mymoviepage.com"

emoji: "✨"

url: "https://www.mymoviepage.com"
cdn: "https://www.mymoviepage.com/assets/"
img: "https://www.mymoviepage.com/assets/img/"
css: "https://www.mymoviepage.com/assets/css/"

author: Tom Bomba
socials: bomtomba

future: false
theme: null

excerpt_separator: <!--more-->

permalink: /:short_year/:month/:title:output_ext
timezone: America/Los_Angeles

collections:
  archives:
    collections_dir: _archives
    output: true
    permalink: "/:path/"
  pages:
    collections_dir: _pages
    output: true
    permalink: "/:path/"

defaults:
  -
    scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      is_post: true
  -
    scope:
      path: "_pages"
      type: "pages"
    values:
      is_page: true
  -
    scope:
      path: "_archives"
      type: "archives"
    values:
      layout: "archives"
      is_archive: true
      is_page: true

markdown: kramdown
kramdown:
    auto_ids: false
    smart_quotes: [lsquo,rsquo,ldquo,rdquo]

sass:
  style: compressed
  sass_dir: _sass

plugins:
  - jekyll-sitemap
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - _vlib
  - _snips
  - .gitignore
  - .DS_Store
  - favicon-package.zip
  - s3_website.yml
