title: "Trash Diary"
name: "Trash"
description: "A media diary, a small collage, a dumb blog"
domain: "www.trashdiary.com"

emoji: "🗑️"

url: "https://www.trashdiary.com"
cdn: "https://www.trashdiary.com/assets/"
img: "https://www.trashdiary.com/assets/img/"
css: "https://www.trashdiary.com/assets/css/"

img_dir: /assets/img/
css_dir: /assets/css/

author: Tom Bomba
socials: bomtomba

safe: true
future: false
theme: null

permalink: /posts/:title:output_ext
timezone: America/Los_Angeles

defaults:
  -
    scope:
      path: ""      # empty string for all files
      type: posts   # limit to posts
    values:
      layout: bahoo
      is_post: true # automatically set is_post=true for all posts
      goog: true

excerpt_separator: <!--more-->

markdown: kramdown
kramdown:
    auto_ids: false
    smart_quotes: [lsquo,rsquo,ldquo,rdquo]

sass:
  style: compressed
  sass_dir: _sass

plugins:
  - jekyll-sitemap
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - _notes
  - _snips
  - .gitignore
  - .DS_Store
  - favicon-package.zip
  - s3_website.yml
