title: "Troubleday"
description: "Tom Bomba's personal blog, where he writes about horror, science fiction, and crime"
domain: "troubleday.com"
url: "https://www.troubleday.com"

author: Tom Bomba
twitter: Troubleday_
letterboxd: t__bomba

img_dir: /assets/img/
css_dir: /assets/css/
ico_dir: /assets/img/ico/

safe: true
future: false
theme: null

include:
  - _pages
  - _pages/archive

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      is_post: true
      style: "post"
  -
    scope:
      path: "_pages"
      type: "pages"
    values:
      layout: "default"
      is_page: true
      style: "page"
  -
    scope:
      path: "_pages/archive"
      type: "pages"
    values:
      layout: "archive"
      is_page: true
      style: "page"

permalink: /:year/:month/:title:output_ext
timezone: America/Los_Angeles

markdown: kramdown
kramdown:
    auto_ids: false
    smart_quotes: [lsquo,rsquo,ldquo,rdquo]

sass:
  style: compressed
  sass_dir: _sass

plugins:
  - jekyll-sitemap
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - _snips
  - .gitignore
  - .DS_Store
  - favicon-package.zip
  - s3_website.yml
