title: "Troubleday"
description: "Short notes on dark genres"
domain: "www.mymoviepage.com"

emoji: "✨"

url: "https://www.mymoviepage.com"
cdn: "https://www.mymoviepage.com/assets/"
img: "https://www.mymoviepage.com/assets/img/"
css: "https://www.mymoviepage.com/assets/css/"

author: Tom Bomba
socials: bomtomba

future: false
theme: null

excerpt_separator: <!--more-->

permalink: /:year/:month/:title:output_ext
timezone: America/Los_Angeles

defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      is_post: true
 
markdown: kramdown
kramdown:
    auto_ids: false
    smart_quotes: [lsquo,rsquo,ldquo,rdquo]

sass:
  style: compressed
  sass_dir: _sass

plugins:
  - jekyll-sitemap
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - .gitignore
  - .DS_Store