title: "Trash Diary"
displayname: "Trash!"
description: "Short notes on dark genres"
domain: "www.trashdiary.com"

url: "https://www.trashdiary.com"
cdn: "https://www.trashdiary.com/assets/"
img: "https://www.trashdiary.com/assets/img/"
css: "https://www.trashdiary.com/assets/css/"

img_dir: /assets/img/
css_dir: /assets/css/

author: Tom Bomba
socials: drashtiary

safe: true
future: false
theme: null

permalink: /posts/:title-:short_year:y_day:output_ext
timezone: America/Los_Angeles

collections:
  pages:
    collections_dir: _pages
    output: true
    permalink: "/:path/"
  genres:
    collections_dir: _genres
    output: true
    permalink: "/:path/"

defaults:
  -
    scope:
      path: ""      # empty string for all files
      type: posts   # limit to posts
    values:
      layout: post
      style: post
      is_post: true # automatically set is_post=true for all posts
  -
    scope:
      path: "_pages"
      type: "pages"
    values:
      layout: "page"
      style: page
      is_page: true
  -
    scope:
      path: ""
      type: "genres"
    values:
      layout: "tag"
      is_page: true

excerpt_separator: <!--more-->

markdown: kramdown
kramdown:
    auto_ids: false
    smart_quotes: [lsquo,rsquo,ldquo,rdquo]

sass:
  style: compressed
  sass_dir: _sass

plugins:
  - jekyll-sitemap
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - _notes
  - _snips
  - .gitignore
  - .DS_Store
  - favicon-package.zip
  - s3_website.yml
