title: "Bomtomba"
description: "A media diary, a small collage, a dumb blog"
domain: "www.bomtomba.com"

favicon: "✨"
emoji: "✌️"

url: "https://www.bomtomba.com"
cdn: "https://www.bomtomba.com/assets/"
img: "https://www.bomtomba.com/assets/img/"
css: "https://www.bomtomba.com/assets/css/"

author: "Tom Bomba"
socials: "bomtomba"

future: false
show_drafts: false
theme: null

permalink: /:year/:month/:title:output_ext
timezone: America/Los_Angeles

collections:
  archives:
    collections_dir: _archives
    output: true
    permalink: "/:path/"

defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      is_post: true
  -
    scope:
      path: "_archives"
      type: "archives"
    values:
      layout: archives
      excerpt: "A list of previous articles"
      is_archive: true

markdown: kramdown
kramdown:
  auto_ids: false
  smart_quotes: [lsquo,rsquo,ldquo,rdquo]

sass:
  style: compressed
  sass_dir: _sass

plugins:
  - jekyll-sitemap
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - .gitignore
  - .DS_Store