title: "Trash diary"
nickname: "!!!"
description: "Short notes on dark genres"
domain: "localhost:4000"

url: "http://localhost:4000"
cdn: "http://localhost:4000/assets/"
img: "http://localhost:4000/assets/img/"
css: "http://localhost:4000/assets/css/"

safe: false
future: false
show_drafts: true