title: "Bomtomba"
description: "A media diary, a small collage, a dumb blog"

url: "https://www.bomtomba.com"

cdn:
  css: "https://www.bomtomba.com/assets/css/"
  img: "https://www.bomtomba.com/assets/img/"

author:
  name: "Tom Bomba"
  nick: "Tom"
  socials: "bomtomba"

future: false
show_drafts: false
theme: null

plugins:
  - jekyll-optional-front-matter
  - jekyll-titles-from-headings
  - jekyll-sitemap
  - jekyll-feed

optional_front_matter:
  remove_originals: true

titles_from_headings:
  enabled:     true
  strip_title: false
  collections: false

sass:
  style: compressed
  sass_dir: _sass

markdown: kramdown
kramdown:
  auto_ids: false
  smart_quotes: [lsquo,rsquo,ldquo,rdquo]

permalink: /:short_year/:title:output_ext
timezone: America/Los_Angeles

collections:
  archives:
    collections_dir: _archives
    output: true
    permalink: "/:path/"
  pages:
    collections_dir: _pages
    output: true
    permalink: "/:path/"

defaults:
  -
    scope:
      path: "_archives"
      type: "archives"
    values:
      layout: year
      excerpt: "A short list of previous posts"
      is_archive: true
  -
    scope:
      path: "_pages"
      type: "pages"
    values:
      is_page: true
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      is_post: true

exclude:
  - Gemfile
  - Gemfile.lock
  - .gitignore
  - .DS_Store
