title: "Localhost"
displayname: "Home!"
description: "A development site"
domain: "localhost:4000"

url: "http://localhost:4000"
cdn: "http://localhost:4000/assets/"
img: "http://localhost:4000/assets/img/"
css: "http://localhost:4000/assets/css/"

safe: false
future: true
show_drafts: false
