title: "Trash Diary"
nickname: "Trash"
description: "Short notes on dark genres"
domain: "www.mymoviepage.com"

emoji: "🗑️"

url: "https://www.mymoviepage.com"
cdn: "https://www.mymoviepage.com/assets/"
img: "https://www.mymoviepage.com/assets/img/"
css: "https://www.mymoviepage.com/assets/css/"

author: Tom Bomba
socials: bomtomba

future: false
theme: null

excerpt_separator: <!--more-->

permalink: /:short_year/:month/:title:output_ext
timezone: America/Los_Angeles

collections:
  pages:
    collections_dir: _pages
    output: true
    permalink: "/:path/"

defaults:
  -
    scope:
      path: "_posts"
      type: posts
    values:
      layout: micro
      is_post: true
  -
    scope:
      path: "_pages"
      type: "pages"
    values:
      is_page: true

markdown: kramdown
kramdown:
    auto_ids: false
    smart_quotes: [lsquo,rsquo,ldquo,rdquo]

sass:
  style: compressed
  sass_dir: _sass

plugins:
  - jekyll-sitemap
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - .gitignore
  - .DS_Store