title: "Troubleday"
description: "a media diary"
domain: "t--bomba.com"
url: "https://www.t--bomba.com"

author: Tom Bomba
twitter: t__bomba
letterboxd: t__bomba

img_dir: /assets/img/
css_dir: /assets/css/

safe: true
future: false

include:
  - _pages
  - _archives

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      is_post: true
  -
    scope:
      path: "_pages"
      type: "pages"
    values:
      layout: "default"
      is_page: true

permalink: /:year/:month/:title:output_ext
timezone: America/Los_Angeles

markdown: kramdown
kramdown:
    auto_ids: false
    smart_quotes: [lsquo,rsquo,ldquo,rdquo]

sass:
  style: compressed
  sass_dir: _sass

plugins:
  - jekyll-sitemap
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - _snips
  - .gitignore
  - .DS_Store
  - favicon-package.zip
  - s3_website.yml
