title: "Bomtomba"
description: "A media diary, a small collage, a dumb blog"
domain: "tombomba.github.io"

url: "https://tombomba.github.io"
cdn: "https://tombomba.github.io/assets/"
img: "https://tombomba.github.io/assets/img/"
css: "https://tombomba.github.io/assets/css/"

img_dir: /assets/img/
css_dir: /assets/css/

author: Tom Bomba
twitter: bomtomba

safe: true
future: false
theme: null

permalink: /:year/:month/:title:output_ext
timezone: America/Los_Angeles

#include:
#  - _pages

collections:
  genres:
    collections_dir: _genres
    output: true
    permalink: "/:path/"

defaults:
  -
    scope:
      path: ""      # empty string for all files
      type: posts   # limit to posts
    values:
      layout: post
      is_post: true # automatically set is_post=true for all posts
  -
    scope:
      path: ""
      type: "genres"
    values:
      layout: "tag"
      is_page: true

markdown: kramdown
kramdown:
    auto_ids: false
    smart_quotes: [lsquo,rsquo,ldquo,rdquo]

sass:
  style: compressed
  sass_dir: _sass

plugins:
  - jekyll-sitemap
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - _snips
  - .gitignore
  - .DS_Store
  - favicon-package.zip
  - s3_website.yml
