title: Troubleday
description: Short notes on dark genres
url: "https://www.troubleday.com"

author: Tom Bomba
twitter: troubleday_
github: tombomba

img_dir: /assets/img/
css_dir: /aseets/css/

future: false

permalink: /:year/:month/:title:output_ext
timezone: America/Los_Angeles

collections:
  archive:
    output: true

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"
      is_post: true
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      is_page: true
  -
    scope:
      path: ""
      type: "archive"
    values:
      layout: "index-by-date"
      is_index: true


markdown: kramdown
kramdown:
    auto_ids: false
    smart_quotes: [lsquo,rsquo,ldquo,rdquo]

sass:
  style: compressed
  sass_dir: _sass

plugins:
  - jekyll-sitemap
  - jekyll-feed

include:
  - _pages

exclude:
  - Gemfile
  - Gemfile.lock
  - _snips
  - .gitignore
  - .DS_Store
  - favicon-package.zip
  - s3_website.yml
