title: Troubleday
description: Short notes on dark genres
url: "https://www.troubleday.com"

author: Tom Bomba
twitter: troubleday_
github: tombomba

img_dir: /assets/img/
css_dir: /assets/css/

safe: true
future: false

permalink: /:year/:month/:title:output_ext
timezone: America/Los_Angeles

markdown: kramdown
kramdown:
    auto_ids: false
    smart_quotes: [lsquo,rsquo,ldquo,rdquo]

sass:
  style: compressed
  sass_dir: _sass

plugins:
  - jekyll-sitemap
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - _snips
  - .gitignore
  - .DS_Store
  - favicon-package.zip
  - s3_website.yml
