title: "Troubleday"
name: "Troubleday"
description: "Short notes on dark genres"
domain: "www.trashdiary.com"

emoji: "✨"

url: "https://www.trashdiary.com"
cdn: "https://www.trashdiary.com/assets/"
img: "https://www.trashdiary.com/assets/img/"
ico: "https://www.trashdiary.com/assets/ico/"
css: "https://www.trashdiary.com/assets/css/"

img_dir: /assets/img/
css_dir: /assets/css/

author: Tom Bomba
socials: bomtomba

future: false
theme: null

excerpt_separator: <!--more-->

permalink: /:short_year/:month/:title:output_ext
timezone: America/Los_Angeles

collections:
  archives:
    collections_dir: _archives
    output: true
    permalink: "/:path/"
  pages:
    collections_dir: _pages
    output: true
    permalink: "/:path/"

defaults:
  -
    scope:
      path: ""      # empty string for all files
      type: posts   # limit to posts
    values:
      layout: text
      is_post: true
  -
    scope:
      path: "diary/_posts"
      type: posts
    values:
      layout: micro
      is_post: true
  -
    scope:
      path: ""
      type: "pages"
    values:
      is_page: true
  -
    scope:
      path: ""
      type: "archives"
    values:
      layout: "archives"
      is_archive: true
      is_page: true

markdown: kramdown
kramdown:
    auto_ids: false
    smart_quotes: [lsquo,rsquo,ldquo,rdquo]

sass:
  style: compressed
  sass_dir: _sass

plugins:
  - jekyll-sitemap
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - _vlib
  - _snips
  - .gitignore
  - .DS_Store
  - favicon-package.zip
  - s3_website.yml
