title: "Localhost"
description: "A media diary, a small collage, a dumb blog"
domain: "localhost:4000"

url: "http://localhost:4000"
cdn:
  css: "http://localhost:4000/assets/css/"
  img: "http://localhost:4000/assets/img/"

safe: true
future: true
show_drafts: false
