title: "trashdiary_"
description: "A small collage, a dumb blog"
domain: "www.bomtomba.com"

url: "https://www.bomtomba.com"
cdn: "https://www.bomtomba.com/assets/"

author: "Tom Bomba"
socials: "trashdiary_"

future: false
show_drafts: false
theme: null

permalink: /p/:title:output_ext
timezone: America/Los_Angeles

collections:
  pages:
    collections_dir: _pages
    output: true
    permalink: "/:path/"

defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      is_post: true
  -
    scope:
      path: "_pages"
      type: "pages"
    values:
      layout: post

markdown: kramdown
kramdown:
  auto_ids: false
  smart_quotes: [lsquo,rsquo,ldquo,rdquo]

sass:
  style: compressed
  sass_dir: _sass

plugins:
  - jekyll-sitemap
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - .gitignore
  - .DS_Store